# Generated by Django 3.2.6 on 2021-10-17 09:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import saleor.core.utils.json_serializer


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('csv', '0004_auto_20210709_1043'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed'), ('deleted', 'Deleted')], default='pending', max_length=50)),
                ('message', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content_file', models.FileField(null=True, upload_to='import_files')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='import_files', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ImportEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('type', models.CharField(choices=[('import_pending', 'Data import was started.'), ('import_success', 'Data import was completed successfully.'), ('import_failed', 'Data import failed.'), ('import_deleted', 'Import file was deleted.'), ('imported_file_sent', 'Email with notify was sent to the customer.'), ('import_failed_info_sent', 'Email with info that import failed was sent to the customer.')], max_length=255)),
                ('parameters', models.JSONField(blank=True, default=dict, encoder=saleor.core.utils.json_serializer.CustomJsonEncoder)),
                ('import_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='import_events', to='csv.importfile')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='import_csv_events', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
